### ISSUE TITLE
The iOS Phone icon looks wrong

### ISSUE THREAD

**Issue by gershik** [d7mtg/d7mtg.github.io#6]
![IMAGE 2022-01-20 20:33:17](https://user-images.githubusercontent.com/31369902/150391484-7199192e-d959-4693-bc54-89dc4414f4f6.jpg)
This is what it should look like on iOS. Here, the gradient is really off.

**Comment by d7mtg** [comment]
Thank you - fixed in commit 66650a9364d8a483d2980434a1a2dcf272bcb636
