### ISSUE TITLE
[english-to-hebrew] Support uppercase English alphabet

### ISSUE THREAD

**Issue by mordechaim** [d7mtg/d7mtg.github.io#7]
https://github.com/d7mtg/d7mtg.github.io/blob/3e9d5c92b0f49e11c6700d07e71391bc99331f35/aleph/V2/index.html#L1014

We need to also support the uppercase alphabet to convert to Hebrew letters.

**Comment by d7mtg** [comment]
Thank you! fixed in commit #fb5b837
