### ISSUE TITLE
[reverse-text] Niqqud gets reversed as well

### ISSUE THREAD

**Issue by mordechaim** [d7mtg/d7mtg.github.io#9]
Being that the Reverse Text tool simply reverses character verbatim is will also shift around Hebrew Niqqud in the wrong place.

The reason of course is because Niqqud characters are diacritic glyphs that always follow the affected characters.

We could say that this is not a bug, but the tool doing its job as described, but being that this is a tool that assists pasting Hebrew text for inputs that don't support bidi, it seems wrong to me.

**Comment by mordechaim** [comment]
If you only care about hebrew, you can replace
https://github.com/d7mtg/d7mtg.github.io/blob/118dcccf61f848f62066ac750b6e2d4b6274e654/aleph/V2/index.html#L1150

with

```js
userInputArray = userInput.match(/.[\u0590-\u05C7]*/g)
```

**Comment by d7mtg** [comment]
Hi! I think it works now, exactly as you said.
